FP-2802-Revert-lib-ide-to-the-version-before-the-MUI-tty-changes
MOV-AI/frontend-npm-lib-ide pull request #315
Opened 2024-06-14 07:23 UTC by EdwardAngeles

# 1.1.3
- [FP-2802 - Revert lib-ide to the version before the MUI / tty changes](https://movai.atlassian.net/browse/FP-2802)

2024-06-14 15:20 UTC, manuelnogueiramov reviewed
Take a look at my comments please.

2024-06-14 15:20 UTC, manuelnogueiramov commented on CHANGELOG.md
> +- [FP-2802 - Revert lib-ide to the version before the MUI / tty changes](https://movai.atlassian.net/browse/FP-2802)
@diasdm and @TiagoLopesQA  we need a decision here.

2024-06-14 15:20 UTC, manuelnogueiramov commented on .gitignore
Please add these as well:

```
# Optional npm cache directory
.npm
.pnpm-store
```

2024-06-14 16:43 UTC, manuelnogueiramov commented on CHANGELOG.md
> +- [FP-2802 - Revert lib-ide to the version before the MUI / tty changes](https://movai.atlassian.net/browse/FP-2802)
According to the discussion with @diasdm you should start using the new nomenclature:
`[ticket_number](ticket_link): ticket small description`

2024-06-14 16:45 UTC, manuelnogueiramov commented on .gitignore
When you run `pnpm install`, it creates over 50.000 files as cache. This adds them to .gitignore.

2024-06-14 16:45 UTC, manuelnogueiramov commented on CHANGELOG.md
> +- [FP-2802 - Revert lib-ide to the version before the MUI / tty changes](https://movai.atlassian.net/browse/FP-2802)
```suggestion
- [FP-2802](https://movai.atlassian.net/browse/FP-2802): Revert lib-ide to the version before the MUI / tty changes
```

2024-06-17 07:57 UTC, diasdm requested changes
Lets start on 1.2.1 since 1.2.0 already exists

2024-06-17 07:57 UTC, diasdm commented on package.json
> +  "version": "1.1.3-0",
```suggestion
  "version": "1.2.1-0",
```

2024-06-17 10:31 UTC, diasdm requested changes

2024-06-17 10:31 UTC, diasdm commented on CHANGELOG.md
> +# 1.1.3
```suggestion
# 1.2.1
```

2024-06-17 10:31 UTC, diasdm commented on CHANGELOG.md
>  # 2.5.0
```suggestion
# 1.1.2
```

2024-06-17 11:00 UTC, diasdm approved these changes

2024-06-17 11:21 UTC, merged