- [FP-2744](https://movai.atlassian.net/browse/FP-2744): Copying nodes in the flow does not copy the modified parameters
MOV-AI/frontend-npm-lib-ide pull request #321
Opened 2024-07-08 09:53 UTC by quirinpa

- [FP-2744](https://movai.atlassian.net/browse/FP-2744): Copying nodes in the flow does not copy the modified parameters

2024-07-08 13:33 UTC, diasdm requested changes
From what we discussed in the meeting, this is a workaround that seems to increase code complexity.
ATM we are getting the node data from the graph and the graph is out dated. Please try to get the data from the model and only the selected node names to copy from the graph

2024-07-09 18:41 UTC, diasdm requested changes
It seems nodeData is not needed

2024-07-10 10:39 UTC, quirinpa commented
What you said about nodeData not being needed holds up to scrutiny. I've removed it.

2024-07-10 10:40 UTC, quirinpa commented
On your first comment. I don't think we can easily achieve things another way for now.
We only have all the data needed in that moment, so we can't really move that up.

2024-07-12 10:32 UTC, manuelnogueiramov approved these changes
Looks nice.

2024-07-12 13:07 UTC, merged