FP-2879: Also resetBoomarks when we have an invalidTab
MOV-AI/frontend-npm-lib-ide pull request #330
Opened 2024-07-26 12:29 UTC by manuelnogueiramov

[FP-2879](https://movai.atlassian.net/browse/FP-2879)

* ~~Added some sanitization to tabStack onMount~~ This has been removed as was causing other issues and the end result wasn't nearly worth it. I did, however, caught an issue where defaultTabStack was being initialized after being called in `workspace.getTabStack()`.
* We are now also reseting boomarks when we have an invalidTab (ie: there's no more tabs)
* Added a filter before we get the tab stack `getTabStack` to clean out `null` or `undefined` values.

The issue that was happening where sometimes we didn't have tabs and the UI would be weird, it might be solved in this PR (not sure as it's not easily replicable.)

**The actual solution to this ticket's issue is efectively in `src/engine/ReactPlugin/EditorReactPlugin.js` in line 97** 
The rest are quality of life improvements, sanitizations and checks.

[FP-2879]: https://movai.atlassian.net/browse/FP-2879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-07-26 15:06 UTC, diasdm requested changes
Solve conflicts pls

2024-07-30 14:39 UTC, diasdm commented on src/utils/Workspace.js
> +      tabStack[dock] = tabStack[dock].filter(x => x).map(tab => ({
Is this needed? Is it something tabStack can do internally?

2024-08-02 08:28 UTC, quirinpa approved these changes

2024-08-02 13:42 UTC, diasdm requested changes
In the morning we agreed this would be the fix for FP-2773 but with the latest changes it no longer does

2024-08-09 09:28 UTC, diasdm approved these changes

2024-08-09 09:33 UTC, merged