FP-2882-Clicking-in-the-bar-under-the-documents-loses-context-not-easy-to-get-back
MOV-AI/frontend-npm-lib-ide pull request #333
Opened 2024-07-31 17:33 UTC by EdwardAngeles

- [FP-2882](https://movai.atlassian.net/browse/FP-2882): Clicking in the bar under the documents loses context, not easy to get back

[FP-2882]: https://movai.atlassian.net/browse/FP-2882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-08-01 11:46 UTC, diasdm requested changes
With this solution we are always activating all loaded editors, can we make this more targeted?

2024-08-02 09:46 UTC, manuelnogueiramov commented on src/engine/ReactPlugin/EditorReactPlugin.js
> +      () => activateEditor(),
I think this will cause a ton of regression bugs :(

2024-08-07 13:25 UTC, diasdm requested changes
If we have a flow and node with the same name open, it can happen that the one not focused is saved

2024-08-07 16:59 UTC, diasdm approved these changes

2024-08-08 08:19 UTC, merged