FP-2988: Can't create Callback from node subscriber port "+" button
MOV-AI/frontend-npm-lib-ide pull request #372
Opened 2024-11-12 10:58 UTC by quirinpa

- [FP-2988](https://movai.atlassian.net/browse/FP-2988): Can't create Callback from node subscriber port "+" button

[FP-2988]: https://movai.atlassian.net/browse/FP-2988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-11-20 12:45 UTC, diasnad approved these changes

2024-11-22 12:55 UTC, manuelnogueiramov requested changes
I think the solution is quite like what you've done, but I'm afraid this way it might cause a racing condition. Having 2 promises running side by side and the last one is dependent on the first. I would suggest using `async` `await` here, this way we know that the promises are called when they are supposed.

2024-11-22 13:16 UTC, manuelnogueiramov commented
> I would agree with that, Manuel.
> 
> Are we ensuring that the promise only resolves if the action is completed?

Didn't understand what you meant here.

2024-11-25 13:13 UTC, quirinpa commented
I meant if it was an asynchronous action, I was asking if we were ensuring that it'd only resolve on completion.

But I looked into it and saw that it wasn't an asynchronous call. So I think your comment does not apply.

2024-12-11 11:25 UTC, quirinpa commented
Even though call returns a promise (in some instances, at least), which it has to to ensure that remix plugin method calling mechanism supports async methods and promises, it doesn't necessarily mean that we have to use an await there.

The code of the function is synchronous. The call implementation most probably calls the function synchronously and returns its result, which might be a promise, or not.

2024-12-12 15:44 UTC, diasnad commented
Did you test both options to see if any would bring regressions?

2024-12-12 19:48 UTC, manuelnogueiramov commented
What issues could adding an await there, that would in fact make sure that we only run the next code after we get the promise, can happen? What am I overlooking?

2025-01-06 13:58 UTC, manuelnogueiramov requested changes
Still waiting on answers.

2025-01-08 12:01 UTC, quirinpa commented
It brings no issues. And takes away no issues.

2025-01-08 12:43 UTC, diasnad commented
To be change to be using `async await`

2025-01-13 19:35 UTC, manuelnogueiramov approved these changes
Perfect :ok_hand: 

Good work! :tada:

2025-01-14 14:51 UTC, diasnad approved these changes

2025-01-14 14:51 UTC, merged