Fp 1013 shift selecting multiple nodes and selecting multiple nodes by shift seeking the mouse are conflicting
MOV-AI/frontend-npm-lib-ide pull request #374
Opened 2024-11-14 13:16 UTC by quirinpa

- [FP-1013](https://movai.atlassian.net/browse/FP-1013): Shift selecting multiple nodes and selecting multiple nodes by shift seeking the mouse are conflicting

2024-11-22 12:29 UTC, manuelnogueiramov requested changes
I don't understand why so many changes. In my point of view, it should be something so simple as only do selection when the user start dragging, not as soon as shift is pressed.
This PR touches a lot of things that I'm not comfortable accepting

2024-11-22 13:10 UTC, quirinpa commented
Be sure to check what it does. I left those things there on purpose.

2024-11-22 13:15 UTC, manuelnogueiramov commented
> Be sure to check what it does. I left those things there on purpose.

I guess you didn't understand my point.
It's not about the solution. I bet it does exactly what was asked of you.
It's about the future regressions that will come out of this. My point is that you are making a lot of changes, for something that wouldn't be needing so many changes. That's just it. Which in turn might create future regressions.

2024-11-25 13:34 UTC, quirinpa commented
I'm happy to cut some of the changes off, but I'd like it if you took a look at what happened in MainInterface.

Since we have talked about moving state to such an api class before and I would like you to understand what I mean.

I have understood your point. But you missed mine.

2025-04-16 15:59 UTC, closed without merging